---

- name: Crate the database
  community.postgresql.postgresql_db:
    db: "{{ zabbix_server_backend_database_name }}"
    login_user: "{{ zabbix_server_backend_database_user }}"
    login_host: "{{ zabbix_server_backend_database_host }}"
    login_password: "{{ zabbix_server_backend_database_password }}"
    owner: "{{ zabbix_server_backend_database_user }}"
    encoding: Unicode

- name: Crate the database from schema files
  community.postgresql.postgresql_db:
    db: "{{ zabbix_server_backend_database_name }}"
    login_user: "{{ zabbix_server_backend_database_user }}"
    login_host: "{{ zabbix_server_backend_database_host }}"
    login_password: "{{ zabbix_server_backend_database_password }}"
    target: "{{ zabbix_server_backend_database_sql_dir }}/{{ item }}"
    state: restore
  with_items: "{{ zabbix_server_backend_database_sql_files }}"

- name: Set zabbix_server_api_login_password
  community.zabbix.zabbix_user:
    passwd: "{{ zabbix_server_api_login_password }}"
    alias: Admin
    login_password: zabbix
    login_user: Admin
    server_url: "{{ zabbix_server_api_server_url }}"
    override_passwd: yes
    usrgrps:
      - Zabbix administrators
