---

- name: Crate the database
  community.postgresql.postgresql_db:
    db: "{{ zabbix_server_backend_database_name }}"
    login_user: "{{ zabbix_server_backend_database_user }}"
    login_host: "{{ zabbix_server_backend_database_host }}"
    login_password: "{{ zabbix_server_backend_database_password }}"
    owner: "{{ zabbix_server_backend_database_user }}"
    encoding: Unicode

- name: Crate the database from schema files
  community.postgresql.postgresql_db:
    db: "{{ zabbix_server_backend_database_name }}"
    login_user: "{{ zabbix_server_backend_database_user }}"
    login_host: "{{ zabbix_server_backend_database_host }}"
    login_password: "{{ zabbix_server_backend_database_password }}"
    target: "{{ zabbix_server_backend_database_sql_dir }}/{{ item }}"
    state: restore
  with_items:
    - schema.sql
    - images.sql
    - data.sql

- name: Set zabbix_server_api_login_password_hash
  community.postgresql.postgresql_query:
    db: "{{ zabbix_server_backend_database_name }}"
    login_user: "{{ zabbix_server_backend_database_user }}"
    login_host: "{{ zabbix_server_backend_database_host }}"
    login_password: "{{ zabbix_server_backend_database_password }}"
    # userid 1 is the default Admin user
    query: "UPDATE users SET passwd = %s WHERE userid = 1"
    positional_args:
      - "{{ zabbix_server_api_login_password_hash }}"
