---

- name: Install py-zabbix-api
  # XXX available at https://github.com/trombik/freebsd-ports-py-zabbix-api
  ansible.builtin.pkgng:
    name: "{{ zabbix_server_python_api_package }}"
    pkgsite: local
    state: present

- name: Install zabbix_server_package
  ansible.builtin.pkgng:
    name: "{{ zabbix_server_package }}"
    pkgsite: local
    state: present

- name: Install zabbix_server_extra_packages
  ansible.builtin.pkgng:
    name: "{{ zabbix_server_extra_packages }}"
    pkgsite: local
    state: present

- name: "Create /etc/rc.conf.d/{{ zabbix_server_service }}"
  ansible.builtin.template:
    src: FreeBSD.rcd.j2
    dest: "/etc/rc.conf.d/{{ zabbix_server_service }}"
    mode: "0644"
    validate: sh -n %s
  notify:
    - Restart zabbix_server

- name: Enable zabbix_server
  ansible.builtin.service:
    name: "{{ zabbix_server_service }}"
    enabled: true
