---

- name: Install py-zabbix-api
  # XXX available at https://github.com/trombik/freebsd-ports-py-zabbix-api
  pkgng:
    name: py38-zabbix-api
    pkgsite: local
    state: present

- name: Install zabbix_server_package
  pkgng:
    name: "{{ zabbix_server_package }}"
    pkgsite: local
    state: present

- name: Install zabbix_server_extra_packages
  pkgng:
    name: "{{ zabbix_server_extra_packages }}"
    pkgsite: local
    state: present
